env: {}
image:
  pullPolicy: IfNotPresent
  repository: nodered/node-red
  tag: latest
persistence:
  data:
    emptyDir: false
    enabled: true
    mountPath: /data
    storageClass: nfs
    accessMode: ReadWriteOnce
    size: 5Gi
service:
  port:
    port: 1880
strategy:
  type: Recreate
hostNetwork: true
timezone: "Europe/Zurich"

ingress:
  enabled: true
  tls: false
  # secretName: my-tls-cert # only needed if tls above is true
  hostname: nodered.192.168.1.220.nip.io
  annotations:
    # kubernetes.io/ingress.class: "nginx"
    # kubernetes.io/tls-acme: "true"

